<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRVzSpcz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRVzSpcz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRVzSpcz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRVzSpcz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRVzSpcz\App_KernelDevDebugContainer([
    'container.build_hash' => 'RVzSpcz',
    'container.build_id' => '638f5d81',
    'container.build_time' => 1605459978,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRVzSpcz');
