# Generated by Django 2.2.4 on 2019-08-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Languages',
        ),
    ]
