# Generated by Django 2.2.4 on 2019-08-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=200)),
                ('Telpon', models.CharField(max_length=15)),
                ('Alamat', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Pria')], max_length=2)),
                ('Tgl_lahir', models.DateField()),
            ],
        ),
    ]
