# Generated by Django 2.2.4 on 2019-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='Gender',
            field=models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], max_length=2),
        ),
    ]
