# Generated by Django 2.2.4 on 2019-08-07 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0004_auto_20190807_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='Email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
